apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: get-ingress-rule
spec:
  ingressClassName: nazure-application-gateway              # nginx
  rules:
   - host: todo-get.abhaysingh.shop
     http:
       paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: get-task-service
              port:
                number: 80